name: playwright
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: playwright/package-lock.json
      - name: Install Playwright dependencies
        run: npx playwright install-deps chromium
        working-directory: playwright
      - name: Run Playwright tests
        run: npx playwright test --trace=retain-on-failure --reporter=dot
        working-directory: playwright
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright/playwright-report
          retention-days: 10
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: playwright/test-results
          retention-days: 10
